### ISSUE TITLE
Generate multiple files from the same template

### ISSUE THREAD

**Issue by alexandru-elisei** [mudrd8mz/moodle-tool_pluginskel#13]
Given the recipe:
```
observers:
    - eventname: core\event\something_happened
      callback: "\local_test\event_observer::something_happened"
      includefile: "/path/to/file/relative/to/moodle/dir/root"
      priority: 200
    - eventname: core\event\something_else_happened
      callback: "\local_test\another_event_observer::something_else_happened"
```
the db/events.php file will be generated from the db_events.mustache template. But I also need to generate two class files: event_observer.php (which contains the class event_observer with the static function something_happened()) and another_event_observer.php (which contains the class another_event_observer with the static function something_else_happened()).

It is reasonable to expect that the two class files are generated from the same template.

You are passing the entire recipe to each file generator class.

How can I generate two different files from the same template and using the same recipe?
