### ISSUE TITLE
Differentiate array variable fields

### ISSUE THREAD

**Issue by alexandru-elisei** [mudrd8mz/moodle-tool_pluginskel#65]
I have experimented with several ways to differentiate the fields for array variables, and what I think the best idea is to have the array index before the field.

For example, let's say that I have the following dependencies in the recipe:

```
dependencies:
    - plugin: mod_newmod
      version: 2016010100
    - plugin: block_test
      version: ANY_VERSION
```

On the web interface the fields will appear like this:

```
0. Plugin: mod_newmod
0. Version: 2016010100

1. Plugin: block_test
1. Version: ANY_VERSION
```

If it's not exactly clear how this will look like I can upload a screenshot.

With nested array variables (for example, capabilities):

```
0. Name
0. Riskbitmask
...
Archetypes:
0.0 Role
0.0 Permission

0.1 Role
0.1 Permission 
```

In case it might look a bit strange to start the numbering from 0 (e.g `0. Plugin`): array indexes start at 0 with most programming languages, I would like to keep it that way on the web interface too. But if it looks too weird I can change it (I'll add 1 to the array index).
