### ISSUE TITLE
\mod_XXX\event\course_module_viewed

### ISSUE THREAD

**Issue by tmuras** [mudrd8mz/moodle-tool_pluginskel#83]
view.php generated for module refers to \mod_XXX\event\course_module_viewed class:
https://github.com/mudrd8mz/moodle-tool_pluginskel/blob/master/skel/file/mod/view.mustache#L36

but the class is not generated. Therefore the view.php of the module generated will trigger the error:

Exception - Class 'mod_php\event\course_module_viewed' not found

**Comment by dvdcastro** [comment]
I had to add these events when creating a `mod_*` kind of plugin.
```
events:
    - eventname: course_module_instance_list_viewed
      extends: \core\event\course_module_instance_list_viewed
    - eventname: course_module_viewed
      extends: \core\event\course_module_viewed
```

They should be suggested, I agree.
